### ISSUE TITLE
One image; Multiple containers; Different commands using docker-compose

### ISSUE THREAD

**Issue by cbwilliamsnh** [docker/hub-feedback#1640]
I'd like to be able to define a single image that will be used for three containers with each container running a different command. I've tried the following with no success. Is there something I'm missing?

```
services:
    service1:
        image: myimage
        build:
          context: ../
          dockerfile: MyDockerfile
        command: ["some-command"]
       ...

    service2:
        image: myimage
        command: ["some-other-command"]
       ...

    service3:
        image: myimage
        command: ["yet-some-other-command"]
       ...
```

but when I examine the running containers after `docker-compose up --build` all three containers show "some-command" as the command used to run the container and the logs support that this is in fact correct.

I know I can do what I want with `docker` commands, but I want to know if there's a way to do it using `docker-compose`.
