### ISSUE TITLE
Configure build rules using a repository file

### ISSUE THREAD

**Issue by cjolowicz** [docker/hub-feedback#1783]
Is it possible to configure build rules for Automated builds using a file in the GitHub repository linked to the Docker Hub repository?

Currently build configuration seems to be possible only via the web interface at https://cloud.docker.com/repository/docker/NAMESPACE/REPO/builds/edit.

An example would be a YAML file specifying build rules like this:

```yaml
--- 
alpine: 
  autobuild: true
  caching: true
  context: /
  location: alpine/Dockerfile
  source: master
  tag: 1.8.0-alpine
  type: branch
ubuntu: 
  autobuild: true
  caching: true
  context: /
  location: ubuntu/Dockerfile
  source: master
  tag: "1.8.0"
  type: branch
```

### Use case

Configuring automated builds for an application on various platforms is very time-confusing with the web interface. This quickly becomes infeasible once the application itself is upgraded to a new version. 

For example, consider the situation where a bug in the Dockerfile is found after upgrading the application. Fixes need to be ported to previous application versions, using a repository branch for each supported version. If this is not feasible, the only alternative would be to remove the images for older versions from Docker Hub.

See https://github.com/cjolowicz/docker-buildbot-worker for an example of a build matrix where a YAML spec would be very helpful.
