### ISSUE TITLE
Slow download speeds while pulling images from HUB

### ISSUE THREAD

**Issue by darki73** [docker/hub-feedback#2172]
## Problem description

Good time of the day.

In a past few days I've started noticing that download speed on `docker pull` became really slow for some reason.
I've read that speeds might be throttled due to the amount of images pulled per 6 hours (100 for anonymous and 200 for authenticated).

However, I am experiencing problem that for a couple of days now (I usually pull 3-10 images per day to update containers on my home server) the download speed became really slow.

I've tried multiple things, even authenticated under my account on my server machine, alas it did nothing.
One source of a problem might be that I am using a static IP address, however, given the amount of images I am pulling during the day, this should have 0 effect on my download speeds.

As of right now, I am trying to build a container based on `nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04` and results are pretty sad to say the least:
``` => => sha256:f68bad238d01924ca5e1d2a3f0bdf2ccf42f742d9a67de0d8d2c0da49661cca0 87.03MB / 1.30GB        329.2s```

Is there anything I can do on my side to help to resolve this problem?

## `docker info` output

Docker Info:
```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 51
  Running: 48
  Paused: 0
  Stopped: 3
 Images: 44
 Server Version: 20.10.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.28-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 125.8GiB
 Name: Tower
 ID: ====redacted====
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: darki73
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Timetamp or time range**: Past 3-5 days

**Public IP**:  Static IP address, already sent on in the support through website

**Hub Username**: darki73

## Screenshots of the issue (if applicable)

![image](https://user-images.githubusercontent.com/1318627/140409507-0e9f1679-0581-4753-bc7e-73592037e8fd.png)

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me
