### ISSUE TITLE
Create repository in new account doesn't seem to work.

### ISSUE THREAD

**Issue by nicolae536** [docker/hub-feedback#2228]
## Problem description
I created a new docker account and tried to push an image to it. The image was pushed it seems.

```
 docker push houzy/frontend-builder:16.13.0
The push refers to repository [docker.io/houzy/frontend-builder]
b46180ce1df2: Pushed
bc9c3df25db5: Pushed
8e09a89e2de7: Pushed
64f1b7900e52: Pushed
bd72fd55c525: Pushed
951e75b1043e: Pushed
bf76199600e0: Pushed
0ddf3378b186: Mounted from library/node
110d3632d653: Mounted from library/node
a46c3bae9c2e: Mounted from library/node
b485db677a87: Mounted from library/node
6cdb6a376c8b: Mounted from library/node
a5e5ff41e5d3: Mounted from library/node
0ac0b7cace95: Mounted from library/node
ee64586bec22: Mounted from library/node
040a44cff5e0: Mounted from library/node
16.13.0: digest: sha256:fc549c8f097cd881c63c41c9b78ed487824fee516a898811a48d8ccc32dbcd1b size: 3675
```

But if I go to the account I cannot see the repository in the repository list.

I tried to create a new repository but it seems I cannot the ui seems to get an error and remains in an infinite loading state after I click create button.

![image](https://user-images.githubusercontent.com/9453094/164425913-746b4a71-b3a4-435a-ae02-73c84ac6d1c9.png)

## `docker info` output

Docker Info:
```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.4.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 31
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.837GiB
 Name: docker-desktop
 ID: 3JOJ:4EAY:W6UL:6GP5:LOSF:T7N3:HPLY:YFTF:UGF2:ES3J:JYX7:ZNQD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

## Debug Information
**Browser name and version**:
Chrome latest version

**URL**:

**Timetamp or time range**: 
Eastern European Summer Time

**Public IP**: 

**Hub Username**:
houzy

## Error messages (on screen or in browser console)
Seems there is a 401 error but I'm logged in 🗡️ 

## Screenshots of the issue (if applicable)

# Task List
- [x ] This is **NOT** a security issue
- [x ] I do **NOT** have a Docker subscription
- [x ] I have looked through other issues and they do **NOT** apply to me
