### ISSUE TITLE
auth.docker.io responding with No Content

### ISSUE THREAD

**Issue by valkum** [docker/hub-feedback#2254]
## Problem description
After upgrading a system of mine I get an empty No Content response from auth.docker.io when trying to fetch images from dockerhub or trying to login using `docker login`.

Using curl for the failed url returns the correct token. I used mitmproxy to check the issue is not on my end. The request is sent, and auth.docker.io responded without any content (even not headers).
Is there a IP x User-Agent ban in place?

## `docker info` output

Docker Info:
```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 23
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-121-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.933GiB
 Name: valkum-ams
 ID: EQLD:6S54:UFWV:6W26:3MEE:6ZKA:YZZC:K3YH:6ISC:RYSL:NIUL:OEUY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

## Debug Information
**Browser name and version**:

**URL**: https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io

**Timetamp or time range**: 2022-07-03 00:00:00-03:00:00 EUROPE/BERLIN

**Public IP**: 51.15.104.78

**Hub Username**:

## Error messages (on screen or in browser console)
Get "https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

## Screenshots of the issue (if applicable)

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me
