### ISSUE TITLE
Pulls from dockerhub after push fail with 'unknown blob'

### ISSUE THREAD

**Issue by jaredlockhart** [docker/hub-feedback#2354]
## Problem description
After pushing a Docker image to Dockerhub, there is a period of time where pulling that image will fail with `unknown blob`, see example pulls:

```
latest: Pulling from mozilla/experimenter
01b5b2efb836: Already exists
5dda314a937a: Already exists
09f5525c15a3: Already exists
99cdff813800: Already exists
7648ab525d5f: Already exists
a1cd0a85803f: Already exists
3c69c3538433: Already exists
14a682ec005f: Already exists
90ad7b9a66e7: Already exists
e20c4c282bb1: Downloading   38.1MB/54.09MB
3162053bf7d2: Download complete
a4906b56eddd: Download complete
15ccc8619f71: Download complete
0b24ec637634: Download complete
3611517b92d5: Download complete
22235e5b6fd2: Downloading  39.61kB/3.842MB
518f4001ad99: Downloading
98a3275f32a1: Waiting
unknown blob

latest: Pulling from mozilla/experimenter
01b5b2efb836: Already exists
5dda314a937a: Already exists
09f5525c15a3: Already exists
99cdff813800: Already exists
7648ab525d5f: Already exists
a1cd0a85803f: Already exists
3c69c3538433: Already exists
14a682ec005f: Already exists
90ad7b9a66e7: Already exists
e20c4c282bb1: Extracting  10.58MB/54.09MB
3162053bf7d2: Download complete
a4906b56eddd: Download complete
15ccc8619f71: Waiting
0b24ec637634: Download complete
3611517b92d5: Download complete
22235e5b6fd2: Downloading
518f4001ad99: Download complete
98a3275f32a1: Download complete
unknown blob

latest: Pulling from mozilla/experimenter
01b5b2efb836: Already exists
5dda314a937a: Already exists
09f5525c15a3: Already exists
99cdff813800: Already exists
7648ab525d5f: Already exists
a1cd0a85803f: Already exists
3c69c3538433: Already exists
14a682ec005f: Already exists
90ad7b9a66e7: Already exists
e20c4c282bb1: Pull complete
3162053bf7d2: Pull complete
a4906b56eddd: Pull complete
15ccc8619f71: Pull complete
0b24ec637634: Pull complete
3611517b92d5: Pull complete
22235e5b6fd2: Pull complete
518f4001ad99: Pull complete
98a3275f32a1: Pull complete
Digest: sha256:6b71c77d392fb07d3b5b969222c1b9df792d4aa06a280da8835625dd84eeb5f8
Status: Downloaded newer image for mozilla/experimenter:latest
docker.io/mozilla/experimenter:latest
```

## `docker info` output

Docker Info:
```yaml
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/jaredlockhart/.docker/cli-plugins/docker-scout

Server:
 Containers: 11
  Running: 4
  Paused: 0
  Stopped: 7
 Images: 29
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 23.45GiB
 Name: docker-desktop
 ID: dc595967-ad76-44be-acd5-178714f55214
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

# Task List
- [ ] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me
