### ISSUE TITLE
Push errors, content -length missing for request

### ISSUE THREAD

**Issue by ganey** [docker/hub-feedback#2467]
Hi,

I'm experiencing push issues for many repositories:

`missing content-length header for request: https://registry-1.docker.io/v2/<company>/<project>/blobs/sha456:<sha>`

we're using the `docker:28` base image in CI to do this:

```
  image: docker:28
  variables:
    LOCAL_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    RELEASE_IMAGE_TAG: <company>/$CI_PROJECT_NAME
  script:
    - echo -n "$DOCKER_REGISTRY_PASS" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - docker pull $LOCAL_IMAGE_TAG
    - if [ "$PreReleaseLabel" ]; then TAG="$PreReleaseLabel"; else TAG="$MajorMinorPatch"; fi
    - docker tag $LOCAL_IMAGE_TAG $RELEASE_IMAGE_TAG:$TAG
    - docker push $RELEASE_IMAGE_TAG:$TAG
```
