### ISSUE TITLE
Unable to find node modules installed globally

### ISSUE THREAD

**Issue by brorbw** [docker/hub-feedback#657]
I get an error from node when trying to use installed modules
It says Unable to find module "xxx"

Dockerfile
```dockerfile
FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y nodejs npm
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install -g http-server lame icy
```

And 

docker-compose.yml
```yaml
version: '2'
services:
  server:
    build: .
    volumes:
      - ./code:/server/code
    command: bash -c "node /server/code/combinedserver.js"
```

Trying to use any of the modules resultet in the error, and i know the modules is installed. I checked manually. If you install with the "-g" option the modules go in "/usr/local/lib/node_modules/". This bug might not be related to Docker at all. But it is worth noticing that install manually either on the host or the container, both works.

As i could not find any related issues, I assume I might be doing something wrong. But in the case im not it would be nice if it got fixed.
Here is my workaround for the problem

Dockerfile
```dockerfile
FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y nodejs npm
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN mkdir server
WORKDIR server
RUN npm install http-server lame icy
```

So insteadof installing globally I install in a dir, in this case called "server". Then i mount the code dir to "/server"

docker-compose.yml
```yaml
version: '2'
services:
  server:
    build: .
    volumes:
      - ./code:/server/code
    command: bash -c "node /server/code/combinedserver.js"
```
