### ISSUE TITLE
SUT works in local, not in the hub

### ISSUE THREAD

**Issue by FranckErnewein** [docker/hub-feedback#696]
Hi,

I have the following docker-compose file in my project

docker-compose.integration.test.yml:

```
version: "2"

services: 
  sut:
    build:
      context: . 
      dockerfile: ./integration/Dockerfile
    networks:
      test:
        aliases: 
          - sut 
    environment: 
      - "SERVICE_URL=http://count-projection:3000"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  count-projection:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      test:
        aliases:
          - count-projection
    environment: 
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  redis:
    image: redis:3.0  
    networks:
      test:
        aliases:
         - redis

networks:
  test:
```

When I run a `docker-compose -f docker-compose.integration.test.yml up` in local (or on other environment), everything is going well, but unfortunately, when It run in the hub, it fails.
The reasons seems to be that the `sut` service can't access to other services (redis, count-projection) during it is running.
`sut` service is written in nodejs and I have the following error when I'm trying to connect to other services:

```
 1) count-projection should return the status:
     Error: getaddrinfo ENOTFOUND count-projection count-projection:3000
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
//...
10) createRedisClient should create a redis client:
     Uncaught Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
      at errnoException (dns.js:28:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

Which means there is a network problem.
Is there something special about networks for "Service Under Test" context ?
How can I emulate the Hub context to run tests on my machine and get the same error ?

my docker environment:

```
Docker version 1.11.1, build 5604cbe
docker-compose version 1.7.1, build 0a9ab35
OSX 10.11.4 (15E65)
```

**Comment by dandreit** [comment]
As of `docker` v

**Comment by dandreit** [comment]
**[SOLVED]**
If you have errors like
- `ECONNREFUSED`
- `ECONNRESET`
- `ENOTFOUND`

with `docker-compose` in `version: "2"`,
that you did not have in `version: "1"`,
maybe you used `links` in v1,
but not set `depends_on` in v2,
to get a similar effect on services startup order.
See https://docs.docker.com/compose/startup-order/.

Example of `docker.compose.test.yml` (extract):
```
services:
  our-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "redis"
  redis:
    image: redis
```

This solved our `networks` problem between redis database, node.js server, and testing service (`sut`), that needed to start upon dependency on each other:
redis ---[then]--> server ---[then]--> test

Hope that helps.

**Important note:** as mentioned in docker documentation, do not only rely on this!
Your application has to be able to manage service readiness before using it
and/or a retry strategy to (get a chance to) connect even after several failures...
