### ISSUE TITLE
Cluster node can't rejoin the cluster in docker swarm after its restart

### ISSUE THREAD

**Issue by w7089** [docker/hub-feedback#899]
Below is yaml used to create MariaDB cluster composed of 2 services mariadb and mariadbSlave. When i first start the services, cluster size is 3 and functioning well. Though after manually stopping container running mariadb service, docker swarm restarts mariadb service and it's not part of the cluster anymore. New cluster of size 1 is started alongside the old cluster of size 2. How to cause the proper failover of the mariadb service so that after restart cluster size will be 3? From documentation of MariaDB cluster, membership is determined by cluster_name and it's the same name in both services. Thanks in advance.

```
version: '2'
services:
    mariadb:
      restart: always
      deploy:
        replicas: 1
      image: ${DOCKER_REPOSITORY}hauptmedia/mariadb:10.1
      command:
        - "--wsrep-new-cluster"
      networks:
        - default_network
      volumes:
        - /mariadb/maria.cnf:/etc/mysql/conf.d/maria.cnf
      environment:
        - CLUSTER_ADDRESS=gcomm://
        - GALERA=On
        - REPLICATION_PASSWORD=test
        - NODE_NAME=masterNode
        - CLUSTER_NAME=cluster
        - MYSQL_ROOT_PASSWORD=test
        - MYSQL_DATABASE=test
        - MYSQL_USER=user
        - MYSQL_PASSWORD=test
    mariadbSlave:
      restart: always
      deploy:
        replicas: 2
      image: ${DOCKER_REPOSITORY}hauptmedia/mariadb:10.1
      networks:
        - default_network
      volumes:
        - /mariadb/maria.cnf:/etc/mysql/conf.d/maria.cnf
      environment:
        - CLUSTER_ADDRESS=gcomm://mariadb,mariadbSlave
        - GALERA=On
        - NODE_NAME=slaveNode
        - REPLICATION_PASSWORD=test
        - CLUSTER_NAME=cluster
        - MYSQL_ROOT_PASSWORD=test
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
```
